from setuptools import setup, find_packages

setup(
    name="enterprise_rag_framework",
    version="0.1.0",
    author="Taimoor Khan",
    author_email="your.email@example.com",
    description="Enterprise-RAG-Framework: A Production-Grade Retrieval Augmented Generation System",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/TaimoorKhan10/Enterprise-RAG-Framework",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
    python_requires=">=3.10",
    install_requires=[
        "numpy>=1.22.0",
        "pandas>=1.5.0",
        "torch>=2.0.0",
        "transformers>=4.30.0",
        "sentence-transformers>=2.2.2",
        "faiss-cpu>=1.7.4",
        "openai>=1.0.0",
        "langchain>=0.1.0",
        "pydantic>=2.0.0",
        "fastapi>=0.100.0",
        "uvicorn>=0.23.0",
        "python-dotenv>=1.0.0",
        "pypdf>=3.15.0",
        "docx2txt>=0.8",
        "beautifulsoup4>=4.12.0",
        "pytesseract>=0.3.10",
        "pillow>=10.0.0",
        "rank_bm25>=0.2.2",
        "tiktoken>=0.5.0",
        "tqdm>=4.66.0",
        "datasets>=2.14.0",
        "matplotlib>=3.7.0",
        "streamlit>=1.26.0",
        "plotly>=5.16.0",
        "pytest>=7.4.0",
        "chromadb>=0.4.15",
    ],
    extras_require={
        "dev": [
            "black>=23.7.0",
            "isort>=5.12.0",
            "flake8>=6.1.0",
            "mypy>=1.5.0",
            "pytest>=7.4.0",
            "pytest-cov>=4.1.0",
            "sphinx>=7.1.0",
            "sphinx-rtd-theme>=1.3.0",
            "jupyter>=1.0.0",
        ],
        "vector_stores": [
            "pinecone-client>=2.2.0",
            "qdrant-client>=1.4.0",
            "weaviate-client>=3.24.0",
        ],
        "ocr": [
            "pytesseract>=0.3.10",
            "pdf2image>=1.16.3",
        ],
        "audio": [
            "whisper>=1.1.10",
        ],
    },
)
